spring.application.name=bca-be
# CUSTOMIZZAZIONE PORTA
server.port=9090

# CONNESSIONE A DB
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5433/bcasvil
spring.datasource.username=postgres
spring.datasource.password=xxxxx

# PARAMETRI PER GESTIONE CONNESSIONE
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.format-sql=true
