spring.application.name=bca-be
# CUSTOMIZZAZIONE PORTA
server.port=9090

# CONNESSIONE A DB
spring.datasource.url=jdbc:sqlite:C:/Devel/workspace/banca-centrale-dell-amicizia/bca-be/db/bca-db.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# PARAMETRI PER GESTIONE CONNESSIONE
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.format-sql=true
